CREATE TABLE IF NOT EXISTS owners
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_name  VARCHAR(30),
    first_name VARCHAR(30)                             NOT NULL,
    email      VARCHAR(254)                            NOT NULL,
    CONSTRAINT pk_owners PRIMARY KEY (id),
    CONSTRAINT uq_owner_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS solutions
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    version   VARCHAR(15)                             NOT NULL,
    owner_id  BIGINT REFERENCES owners (id) ON DELETE SET NULL,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT uq_product_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS developers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_name  VARCHAR(30),
    first_name VARCHAR(30)                             NOT NULL,
    email      VARCHAR(254)                            NOT NULL,
    CONSTRAINT pk_developers PRIMARY KEY (id),
    CONSTRAINT uq_developer_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS solutions_developers
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    solutions_id   BIGINT REFERENCES solutions (id) ON DELETE CASCADE,
    developer_id BIGINT REFERENCES developers (id) ON DELETE CASCADE,
    CONSTRAINT pk_solutions_developers PRIMARY KEY (id),
    CONSTRAINT uq_solutions_developers UNIQUE (solutions_id, developer_id)
);
